# Bài tập 2 — Làm sạch và hợp nhất dữ liệu

**Người phụ trách:** Nguyễn Bá Công, Hà Trọng Hữu Duy

---

## Mục tiêu

Đưa 3 nguồn về một bộ dữ liệu sạch, thống nhất:

1. Ánh xạ về schema chung
2. Tách tin bán / tin cho thuê
3. Lọc phạm vi TP.HCM
4. Chuẩn hóa nhãn loại hình
5. Lọc ngoại lai
6. Loại trùng chéo nguồn

In [1]:
# Thiết lập đường dẫn để import được module src/
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 200)

## 1. Chạy toàn bộ pipeline làm sạch

Toàn bộ logic nằm trong `src/data/lam_sach_du_lieu.py` để có thể chạy lại bằng dòng lệnh.

In [2]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\hatro\anaconda3\lib\site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from src.data.lam_sach_du_lieu import chay_pipeline

df_sach = chay_pipeline()

============================================================
BƯỚC 1: ĐỌC DỮ LIỆU TỪ 3 NGUỒN
============================================================
  [CafeLand]    đọc được 9,883 dòng
  [batdongsan]  đọc được 30,149 dòng
  ⚠️  Bỏ qua [chotot]: không tìm thấy chotot_bds_dataset.csv

============================================================
TÓM TẮT: SAU KHI GỘP 3 NGUỒN
============================================================
Kích thước      : 40,032 dòng × 9 cột
Trùng lặp toàn bộ: 0 dòng
Thiếu dữ liệu   :
    quan_huyen                      40,032 (100.0%)
    loai_hinh                        8,776 ( 21.9%)
    dien_tich_m2                     1,295 (  3.2%)
    gia_ban                            914 (  2.3%)
    mo_ta_dac_diem                     422 (  1.1%)

============================================================
BƯỚC 2: TÁCH TIN BÁN / TIN CHO THUÊ
============================================================
  Tin BÁN : 38,582
  Tin THUÊ: 1,450 (sẽ loại bỏ)

============================================================
BƯỚC 3: LỌC PHẠM VI TP.HCM
============================================================
  Lọc TP.HCM: 38,582 -> 36,339 dòng (loại 2,243)

============================================================
BƯỚC 4: CHUẨN HÓA NHÃN LOẠI HÌNH
============================================================
  Số nhãn sau chuẩn hóa: 12
    Nhà rieng              9,445
    Đất                    6,477
    căn hộ                 5,401
    Nhà phố                2,458
    Biệt thự               2,362
    Nhà mặt tiền           1,936
    Shophouse                272
    Nhà hàng - Khách sạn      66
    Kho - Nhà xưởng           57
    Bán đất nông, lâm nghiệp      14
    Bán nhà hàng - Khách sạn      14
    Bán kho, nhà xưởng        11
  Số dòng thiếu loai_hinh: 7,826

============================================================
BƯỚC 5: LOẠI DÒNG THIẾU GIÁ HOẶC DIỆN TÍCH
============================================================
  36,339 -> 34,736 (loại 1,603)

============================================================
BƯỚC 6: LỌC NGOẠI LAI
============================================================
  Lọc ngưỡng cứng: 34,736 -> 34,222
  Lọc IQR (hệ số 3.0): -> 29,799
  Tổng cộng loại: 4,937 dòng ngoại lai

============================================================
BƯỚC 7: LOẠI TRÙNG LẶP
============================================================
  Loại trùng URL nội bộ: 29,799 -> 29,799
  Loại trùng chéo nguồn: 29,799 -> 29,532 (loại 267)

============================================================
BƯỚC 8: TẠO BIẾN PHÁI SINH
============================================================
  Đã tạo cột: gia_moi_m2_trieu

============================================================
KẾT QUẢ CUỐI CÙNG
============================================================

============================================================
TÓM TẮT: DỮ LIỆU SẠCH
============================================================
Kích thước      : 29,532 dòng × 10 cột
Trùng lặp toàn bộ: 0 dòng
Thiếu dữ liệu   :
    quan_huyen                      29,532 (100.0%)
    loai_hinh                        6,703 ( 22.7%)
    mo_ta_dac_diem                       4 (  0.0%)

Phân bố theo nguồn:
    batdongsan       23,370 ( 79.1%)
    cafeland          6,162 ( 20.9%)

✅ Đã lưu: C:\Users\hatro\Downloads\du-doan-gia-nha-dat-hcm-HuuDuy-s-Branch\du-doan-gia-nha-dat-hcm\data\processed\du_lieu_sach.csv

## 2. Kiểm tra kết quả

In [4]:
from src.utils import tom_tat_dataframe

tom_tat_dataframe(df_sach, 'DỮ LIỆU SẠCH')
df_sach.head(10)

============================================================
TÓM TẮT: DỮ LIỆU SẠCH
============================================================
Kích thước      : 29,532 dòng × 10 cột
Trùng lặp toàn bộ: 0 dòng
Thiếu dữ liệu   :
    quan_huyen                      29,532 (100.0%)
    loai_hinh                        6,703 ( 22.7%)
    mo_ta_dac_diem                       4 (  0.0%)

,tieu_de,gia_ban,dien_tich_m2,tinh_thanh,quan_huyen,mo_ta_dac_diem,loai_hinh,nguon_du_lieu,url,gia_moi_m2_trieu
0,"Bán căn hộ 2PN 2WC 74,8m2 full NT The Sun Aven...",7000.0,74.8,TP. Hồ Chí Minh,NaN,"Căn hộ chung cư tại The Sun Avenue, Mai Chí Th...",căn hộ,cafeland,https://nhadat.cafeland.vn/ban-can-ho-2pn-2wc-...,93.582888
1,Bán nhà riêng: KINH DƯƠNG VƯƠNG–NHÀ MỚI 2 MẶT ...,7600.0,64.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Một căn ...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-kinh-...,118.750000
2,Bán nhà riêng: MẶT TIỀN KINH DOANH ĐỈNH – KHU ...,8800.0,76.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh MẶT TIỀN...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-mat-t...,115.789474
3,Bán nhà riêng: SIÊU TỐC – NHÀ ĐẸP FULL NỘI THẤ...,7300.0,56.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng Đường số 7, An Lạc, TP. Hồ Chí M...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-sieu-...,130.357143
4,Bán nhà riêng: Bán Nhà riêng 80m2 thổ cư giá 5...,5300.0,80.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Giá : 5....",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-ban-n...,66.250000
5,Bán nhà riêng: Bán nhà 100m2- 6.98 tỷ tại Vo V...,6980.0,100.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh HẠ GIÁ G...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-ban-n...,69.800000
6,Bán nhà riêng: Bán nhà mặt tiền đường Nhánh An...,8900.0,90.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Bán nhà ...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-ban-n...,98.888889
7,Bán nhà riêng: KHU VIP TÊN LỬA – NHÀ NGANG 6.5...,5200.0,43.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Hàng hiế...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-khu-v...,120.930233
8,Bán nhà riêng: Bán Nhà Mới 60 m2 giá 5.8 tỷ tạ...,5800.0,60.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Bán Nhà ...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-ban-n...,96.666667
9,"Bán nhà riêng: Sợ mua nhà hẻm nhỏ, xe khó vào?...",7200.0,54.0,TP. Hồ Chí Minh,NaN,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Căn nhà ...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-so-mu...,133.333333

In [5]:
# Thống kê mô tả các biến số
df_sach[['gia_ban', 'dien_tich_m2', 'gia_moi_m2_trieu']].describe()

            gia_ban  dien_tich_m2  gia_moi_m2_trieu
count  29532.000000  29532.000000      29532.000000
mean    9227.348300     79.282021        135.091230
std     8016.386039     45.802063        109.499679
min      100.000000     10.000000          0.497674
25%     3895.000000     48.000000         57.142857
50%     6700.000000     68.000000        108.908730
75%    11900.000000    100.000000        185.937500
max    44000.000000    270.000000       2500.000000

## 3. Kiểm chứng chất lượng dữ liệu

Một số kiểm tra bắt buộc trước khi chuyển sang bước EDA.

In [6]:
# Kiểm tra 1: Không còn giá trị âm hoặc bằng 0
print("Giá <= 0      :", (df_sach['gia_ban'] <= 0).sum())
print("Diện tích <= 0:", (df_sach['dien_tich_m2'] <= 0).sum())

# Kiểm tra 2: Không còn dòng trùng URL
print("Trùng URL     :", df_sach['url'].duplicated().sum())

# Kiểm tra 3: Chỉ còn TP.HCM
print("\nCác tỉnh/thành còn lại:")
print(df_sach['tinh_thanh'].value_counts())

Giá <= 0      : 0
Diện tích <= 0: 0
Trùng URL     : 0

Các tỉnh/thành còn lại:
tinh_thanh
TP. Hồ Chí Minh    29532
Name: count, dtype: int64

In [7]:
# Kiểm tra 4: Phân bố theo nguồn
# Nếu một nguồn chiếm tỷ trọng quá lớn, cần lưu ý khi diễn giải kết quả
phan_bo = df_sach['nguon_du_lieu'].value_counts()
print(phan_bo)
print()
print((phan_bo / len(df_sach) * 100).round(1).astype(str) + ' %')

nguon_du_lieu
batdongsan    23370
cafeland       6162
Name: count, dtype: int64

nguon_du_lieu
batdongsan    79.1 %
cafeland      20.9 %
Name: count, dtype: object

## 4. Lọc và suy đoán quận/huyện.

sử dụng thư viện re, để trích xuất các quanba

In [8]:
import re
import pandas as pd


def lam_sach_quan_huyen_tu_mo_ta(df):
    """
    Trích xuất Quận/Huyện từ cột Mo_ta_Dac_diem.

    Hỗ trợ:
        Quận 1 -> Quận 12
        Quận Nhà Bè
        Gò Vấp
        Tân Bình
        Bình Tân
        Bình Thạnh
        Hóc Môn
        Tân Phú
        Thủ Đức

    Không xử lý Phường/Xã.

    Chỉ điền vào df['quan'] nếu giá trị hiện tại đang thiếu.
    """

    df = df.copy()

    if "quan_huyen" not in df.columns:
        df["quan_huyen"] = pd.NA

    if "mo_ta_dac_diem" not in df.columns:
        raise KeyError("Không tìm thấy cột 'Mo_ta_Dac_diem'")

    def trich_quan(text):
        if pd.isna(text):
            return None

        text = str(text)

        # Chuẩn hóa khoảng trắng
        text = re.sub(r"\s+", " ", text).strip()

        # Chuyển về chữ thường để tìm kiếm
        text_lower = text.lower()

        # --------------------------------------------------
        # QUẬN 1 -> QUẬN 12
        # --------------------------------------------------
        match = re.search(
            r"\bquận\s*(1[0-2]|[1-9])\b",
            text_lower
        )

        if match:
            return f"Quận {match.group(1)}"

        # Hỗ trợ dạng Q.1 / Q1 / Q. 1
        match = re.search(
            r"\bq\.?\s*(1[0-2]|[1-9])\b",
            text_lower
        )

        if match:
            return f"Quận {match.group(1)}"

        # --------------------------------------------------
        # CÁC QUẬN/HUYỆN THEO TÊN
        # --------------------------------------------------

        danh_sach = [
            ("bình thạnh", "Quận Bình Thạnh"),
            ("gò vấp", "Quận Gò Vấp"),
            ("tân bình", "Quận Tân Bình"),
            ("bình tân", "Quận Bình Tân"),
            ("tân phú", "Quận Tân Phú"),
            ("nhà bè", "Huyện Nhà Bè"),
            ("hóc môn", "Huyện Hóc Môn"),
            ("thủ đức", "TP. Thủ Đức"),
        ]

        for tu_khoa, ket_qua in danh_sach:
            if tu_khoa in text_lower:
                return ket_qua

        return None

    # Trích xuất
    df["_quan_trich_xuat"] = df["mo_ta_dac_diem"].apply(trich_quan)

    # Chỉ điền vào dòng đang thiếu
    mask = (
        df["quan_huyen"].isna()
        | df["quan_huyen"].astype(str).str.strip().eq("")
    )

    df.loc[mask, "quan_huyen"] = df.loc[mask, "_quan_trich_xuat"]

    # Xóa cột tạm
    df.drop(columns=["_quan_trich_xuat"], inplace=True)

    return df
df_sach=lam_sach_quan_huyen_tu_mo_ta(df_sach)
df_sach

C:\Users\hatro\AppData\Local\Temp\ipykernel_7552\3305661763.py:95: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Quận 2' None None ... 'Quận Bình Tân' 'Quận 5' None]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask, "quan_huyen"] = df.loc[mask, "_quan_trich_xuat"]

,tieu_de,gia_ban,dien_tich_m2,tinh_thanh,quan_huyen,mo_ta_dac_diem,loai_hinh,nguon_du_lieu,url,gia_moi_m2_trieu
0,"Bán căn hộ 2PN 2WC 74,8m2 full NT The Sun Aven...",7000.0,74.8,TP. Hồ Chí Minh,Quận 2,"Căn hộ chung cư tại The Sun Avenue, Mai Chí Th...",căn hộ,cafeland,https://nhadat.cafeland.vn/ban-can-ho-2pn-2wc-...,93.582888
1,Bán nhà riêng: KINH DƯƠNG VƯƠNG–NHÀ MỚI 2 MẶT ...,7600.0,64.0,TP. Hồ Chí Minh,None,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Một căn ...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-kinh-...,118.750000
2,Bán nhà riêng: MẶT TIỀN KINH DOANH ĐỈNH – KHU ...,8800.0,76.0,TP. Hồ Chí Minh,None,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh MẶT TIỀN...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-mat-t...,115.789474
3,Bán nhà riêng: SIÊU TỐC – NHÀ ĐẸP FULL NỘI THẤ...,7300.0,56.0,TP. Hồ Chí Minh,None,"Bán nhà riêng Đường số 7, An Lạc, TP. Hồ Chí M...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-sieu-...,130.357143
4,Bán nhà riêng: Bán Nhà riêng 80m2 thổ cư giá 5...,5300.0,80.0,TP. Hồ Chí Minh,None,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Giá : 5....",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-ban-n...,66.250000
...,...,...,...,...,...,...,...,...,...,...
29527,Nhà Cách Biển 100m Sẵn Mô Hình Kinh Dôanh Cafe...,28000.0,231.0,TP. Hồ Chí Minh,None,Trang chủ / Bán Nhà / Nha Trang / Khánh Hòa / ...,NaN,batdongsan,https://batdongsan.vn/nha-cach-bien-100m-san-m...,121.212121
29528,MT TÂN PHÚ GIÁP TÂN BÌNH - VỊ TRÍ ĐỘC - CHỦ LÀ...,9200.0,80.0,TP. Hồ Chí Minh,Quận Tân Bình,Trang chủ / Bán Nhà / Tân Phú / Hồ Chí Minh / ...,NaN,batdongsan,https://batdongsan.vn/mt-tan-phu-giap-tan-binh...,115.000000
29529,BÁN NHÀ 5 TẦNG BHHB LIÊN KHU 5-6 GIÁ 6.95 TỶ HXH,6950.0,80.0,TP. Hồ Chí Minh,Quận Bình Tân,Trang chủ / Bán Nhà / Bình Tân / Hồ Chí Minh /...,Nhà rieng,batdongsan,https://batdongsan.vn/ban-nha-5-tang-bhhb-lien...,86.875000
29530,𝐂𝐇𝐈𝐍𝐇 𝐓𝐇𝐔̛́𝐂 𝐍𝐇𝐀̣̂𝐍 𝐁𝐎𝐎𝐊𝐈𝐍𝐆 – 𝐓𝐇𝐄 𝐖𝐄𝐒𝐓𝐈𝐐𝐔𝐄,2900.0,40.0,TP. Hồ Chí Minh,Quận 5,Giới hạn chỉ 99 căn - đặc quyền sở hữu chỉ dàn...,căn hộ,cafeland,https://nhadat.cafeland.vn/chinh-thuc-nhan-boo...,72.500000
29531,𝐆𝐈𝐎̉ 𝐇𝐀̀𝐍𝐆 𝐂𝐇𝐔𝐘𝐄̂̉𝐍 𝐍𝐇𝐔̛𝐎̛̣𝐍𝐆 𝐓𝐇𝐄 𝐋𝐈𝐆𝐇𝐓 𝐂𝐈𝐓𝐘,5900.0,100.0,TP. Hồ Chí Minh,None,️ 𝐆𝐈𝐎̉ 𝐇𝐀̀𝐍𝐆 𝐂𝐇𝐔𝐘𝐄̂̉𝐍 𝐍𝐇𝐔̛𝐎̛̣𝐍𝐆 𝐓𝐇𝐄 𝐋𝐈𝐆𝐇𝐓 𝐂𝐈𝐓𝐘...,Nhà phố,cafeland,https://nhadat.cafeland.vn/gio-hang-chuyen-nhu...,59.000000

In [9]:
df_sach = df_sach.dropna(subset=["quan_huyen"])

In [10]:
df_sach.shape

(11888, 10)

In [11]:
import pandas as pd

def loc_outlier_iqr(df, columns=['gia_ban', 'dien_tich_m2']):
    """
    Lọc bỏ các dòng chứa outlier dựa trên phương pháp IQR.
    """
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        df_filtered = df[
            (df[col].isna()) | 
            ((df[col] >= lower_bound) & (df[col] <= upper_bound))
        ]
    return df_filtered
df_sach = loc_outlier_iqr(df_sach, columns=['gia_ban', 'dien_tich_m2'])
df_sach

,tieu_de,gia_ban,dien_tich_m2,tinh_thanh,quan_huyen,mo_ta_dac_diem,loai_hinh,nguon_du_lieu,url,gia_moi_m2_trieu
0,"Bán căn hộ 2PN 2WC 74,8m2 full NT The Sun Aven...",7000.0,74.8,TP. Hồ Chí Minh,Quận 2,"Căn hộ chung cư tại The Sun Avenue, Mai Chí Th...",căn hộ,cafeland,https://nhadat.cafeland.vn/ban-can-ho-2pn-2wc-...,93.582888
5,Bán nhà riêng: Bán nhà 100m2- 6.98 tỷ tại Vo V...,6980.0,100.0,TP. Hồ Chí Minh,Quận 6,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh HẠ GIÁ G...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-ban-n...,69.800000
6,Bán nhà riêng: Bán nhà mặt tiền đường Nhánh An...,8900.0,90.0,TP. Hồ Chí Minh,Quận 6,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Bán nhà ...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-ban-n...,98.888889
7,Bán nhà riêng: KHU VIP TÊN LỬA – NHÀ NGANG 6.5...,5200.0,43.0,TP. Hồ Chí Minh,Quận Bình Tân,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Hàng hiế...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-khu-v...,120.930233
8,Bán nhà riêng: Bán Nhà Mới 60 m2 giá 5.8 tỷ tạ...,5800.0,60.0,TP. Hồ Chí Minh,Quận Bình Tân,"Bán nhà riêng An Lạc, TP. Hồ Chí Minh Bán Nhà ...",Nhà rieng,cafeland,https://nhadat.cafeland.vn/ban-nha-rieng-ban-n...,96.666667
...,...,...,...,...,...,...,...,...,...,...
29523,🏡 NHÀ PHỐ BÌNH TÂN – DỰ ÁN BẢO TÂN RESIDENCE –...,7300.0,80.0,TP. Hồ Chí Minh,Quận Bình Tân,Trang chủ / Bán Nhà / Bình Tân / Hồ Chí Minh /...,Nhà phố,batdongsan,https://batdongsan.vn/nha-pho-binh-tan-du-an-b...,91.250000
29524,"Nhà đẹp mặt tiền Hà Huy Giáp, Q12. (gần ngã 4 ga)",17300.0,113.0,TP. Hồ Chí Minh,Quận 12,Trang chủ / Bán Nhà / Quận 12 / Hồ Chí Minh / ...,Nhà mặt tiền,batdongsan,https://batdongsan.vn/nha-dep-mat-tien-ha-huy-...,153.097345
29528,MT TÂN PHÚ GIÁP TÂN BÌNH - VỊ TRÍ ĐỘC - CHỦ LÀ...,9200.0,80.0,TP. Hồ Chí Minh,Quận Tân Bình,Trang chủ / Bán Nhà / Tân Phú / Hồ Chí Minh / ...,NaN,batdongsan,https://batdongsan.vn/mt-tan-phu-giap-tan-binh...,115.000000
29529,BÁN NHÀ 5 TẦNG BHHB LIÊN KHU 5-6 GIÁ 6.95 TỶ HXH,6950.0,80.0,TP. Hồ Chí Minh,Quận Bình Tân,Trang chủ / Bán Nhà / Bình Tân / Hồ Chí Minh /...,Nhà rieng,batdongsan,https://batdongsan.vn/ban-nha-5-tang-bhhb-lien...,86.875000
29530,𝐂𝐇𝐈𝐍𝐇 𝐓𝐇𝐔̛́𝐂 𝐍𝐇𝐀̣̂𝐍 𝐁𝐎𝐎𝐊𝐈𝐍𝐆 – 𝐓𝐇𝐄 𝐖𝐄𝐒𝐓𝐈𝐐𝐔𝐄,2900.0,40.0,TP. Hồ Chí Minh,Quận 5,Giới hạn chỉ 99 căn - đặc quyền sở hữu chỉ dàn...,căn hộ,cafeland,https://nhadat.cafeland.vn/chinh-thuc-nhan-boo...,72.500000

In [12]:
df_sach = df_sach.dropna(subset=["loai_hinh"])

In [13]:
df_sach.shape

(8516, 10)

## 4. Nhận xét về quá trình làm sạch

*(Viết nhận xét tại đây — đây là phần giảng viên sẽ hỏi kỹ)*

**Cần trả lời được:**
1. Đã loại bao nhiêu dòng ở mỗi bước? Vì sao?<br>
Ban đầu: 29.532 dòng × 11 cột.
Kiểm tra chất lượng dữ liệu:
Giá bán ≤ 0: 0 dòng
Diện tích < 0: 0 dòng
URL trùng: 0 dòng
→ Không loại bỏ dòng nào ở bước này.
Lọc và trích xuất quận từ mô tả: không làm thay đổi số lượng dòng.
Lọc outlier: từ 29.532 dòng xuống còn 27.204 dòng, tức đã loại 2.328 dòng.
Mục đích của bước lọc outlier là loại bỏ những tin có giá bán hoặc diện tích quá bất thường, có thể gây ảnh hưởng đến kết quả phân tích/mô hình.
2. Ngưỡng lọc outlier chọn thế nào? Căn cứ vào đâu?

Sử dụng phương pháp IQR (Interquartile Range). Với mỗi biến cần kiểm tra outlier, tính:

$$ IQR = Q_3 - Q_1 $$

Trong đó:

\(Q_1\): phân vị thứ 25%
\(Q_3\): phân vị thứ 75%

Sau đó xác định ngưỡng:

$$ LowerBound = Q_1 - 1.5 \times IQR $$ $$ UpperBound = Q_3 + 1.5 \times IQR $$

Một giá trị được xem là outlier nếu:

$$ x < Q_1 - 1.5IQR $$

hoặc

$$ x > Q_3 + 1.5IQR $$

Các giá trị nằm trong khoảng:

$$ [Q_1 - 1.5IQR,\ Q_3 + 1.5IQR] $$

được giữ lại.

Căn cứ chọn ngưỡng 1.5 × IQR: đây là quy tắc Tukey phổ biến để xác định các giá trị bất thường dựa trên phân phối của chính dữ liệu, không phụ thuộc vào giả định dữ liệu phải phân phối chuẩn. Đồng thời, trong dữ liệu bất động sản, giá và diện tích thường có phân phối lệch nên IQR phù hợp hơn việc chỉ dùng trung bình và độ lệch chuẩn.

Lưu ý: các giá trị NaN được giữ lại trong bước lọc outlier, vì NaN không thể được kết luận là outlier chỉ dựa trên IQR.